### ISSUE TITLE
Can't compile i3-gaps-next

### ISSUE THREAD

**Issue by ghost** [pvalkone/freebsd-ports#1]
Hey I was trying to use i3-gaps-next from your ports tree and it's not working here. Wondering if you might have any ideas whats going on.

```
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for mode_t... no
configure: error: in `/usr/home/gregf/freebsd-ports/x11-wm/i3-gaps-next/work/i3-9f4226d/build':
configure: error: cannot find required type
See `config.log' for more details
*** Error code 1

Stop.
make: stopped in /usr/home/gregf/freebsd-ports/x11-wm/i3-gaps-next

```

FreeBSD betsy.home.lan 11.0-STABLE FreeBSD 11.0-STABLE #0 r317338: Sun Apr 23 07:09:22 EDT 2017     root@betsy.home.lan:/usr/obj/usr/src/sys/GENERIC  amd64

Thanks!

**Comment by pvalkone** [comment]
Hi, and sorry for the belated reply.

I'm afraid I haven't bumped into the problem you're describing myself.

The output mentions `${WRKSRC}/build/config.log`. Have you checked it for any clues?

I also see that you're running 11.0-STABLE, while I'm currently on 11.0-RELEASE-p9. On my build system, `mode_t` is detected OK (see [this](https://gist.github.com/pvalkone/f8bf7f57681468c200288e1686db51ca) Synth build log).

**Comment by ghost** [comment]
I was having a lot of strange issues with my machine at the time. Not entirely sure what happened. But a rebuild of world seemed to fix most issues. Sorry for the bad report.
